import importlib.util
import pathlib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
PROVENANCE = (ROOT / 'IP_PROVENANCE.md').read_text(encoding='utf-8')
SCRIPT_PATH = ROOT / 'tools' / 'ip_provenance_check.py'
SCRIPT = SCRIPT_PATH.read_text(encoding='utf-8')
NOTICES = (ROOT / 'THIRD_PARTY_NOTICES.txt').read_text(encoding='utf-8')


def load_scanner_module():
    spec = importlib.util.spec_from_file_location('ip_provenance_check', SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class IpProvenanceContractTests(unittest.TestCase):
    def test_automated_evidence_never_claims_legal_signoff(self):
        self.assertIn('HUMAN-LEGAL SIGN-OFF PENDING', PROVENANCE)
        self.assertIn('human_review_required', SCRIPT)
        self.assertIn('legal_signoff_required', SCRIPT)
        self.assertIn('Git history must not be rewritten', PROVENANCE)

    def test_manifest_hashes_governed_source(self):
        self.assertIn('git", "ls-files', SCRIPT)
        self.assertIn('sha256', SCRIPT)
        self.assertIn('review_findings', SCRIPT)
        self.assertIn('header-oriented provenance/license markers', SCRIPT)

    def test_marker_detection_rejects_generic_generated_by_prose(self):
        scanner = load_scanner_module()
        self.assertEqual(scanner.find_review_markers('state generated by the fresh smoke'), [])
        self.assertIn('generated by', scanner.find_review_markers('# Generated by Acme Tool\n'))

    def test_marker_detection_catches_header_license_markers(self):
        scanner = load_scanner_module()
        self.assertIn('do not edit', scanner.find_review_markers('// Do not edit this generated file\n'))
        self.assertIn('licensed under the apache license', scanner.find_review_markers('# Licensed under the Apache License, Version 2.0\n'))
        self.assertIn('copyright (c)', scanner.find_review_markers('# Copyright (c) Example Corp\n'))

    def test_third_party_boundaries_cover_all_platform_artifacts(self):
        for token in ('Python', 'Tcl/Tk', 'PyInstaller', 'AppImage type-2 runtime', 'Inno Setup', 'NetworkManager/PolicyKit'):
            self.assertIn(token, NOTICES)

    def test_clean_tag_remains_blocked_until_human_review(self):
        self.assertIn('Clean IP baseline/tag', PROVENANCE)
        self.assertIn('BLOCKED', PROVENANCE)


if __name__ == '__main__':
    unittest.main()
