#!/usr/bin/env python3
"""Generate deterministic APL-IP-001 source provenance evidence."""
import hashlib
import json
import os
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "artifacts" / "ip-provenance" / "source-manifest.json"
GOVERNED_SUFFIXES = {".py", ".ps1", ".sh", ".command", ".iss", ".yml", ".yaml", ".md", ".txt"}
GOVERNED_NAMES = {"LICENSE", "VERSION", "BUILD_PYTHON_VERSION"}
REVIEW_MARKERS = (
    "generated by ",
    "do not edit",
    "copyright (c)",
    "copyright ©",
    "licensed under the apache license",
    "gnu general public license",
    "mozilla public license",
)
EXCLUDED_PREFIXES = ("artifacts/", "dist/", "build/", ".cache/", ".venv/")


def git_files():
    result = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT, stdout=subprocess.PIPE, check=True)
    return [pathlib.PurePosixPath(p.decode("utf-8")) for p in result.stdout.split(b"\0") if p]


def category(path):
    value = path.as_posix()
    if value.startswith("tests/"):
        return "test"
    if value.startswith(".github/") or value.startswith(".gitverse/"):
        return "ci"
    if value.startswith("docs/") or path.suffix.lower() == ".md":
        return "documentation"
    if value.startswith("tools/") or path.suffix.lower() in {".ps1", ".sh", ".command", ".iss"}:
        return "build-release"
    if path.suffix.lower() == ".py":
        return "product-source"
    return "governance-config"


def main():
    records = []
    review = []
    for relative in sorted(git_files(), key=lambda p: p.as_posix()):
        value = relative.as_posix()
        if value.startswith(EXCLUDED_PREFIXES):
            continue
        if relative.suffix.lower() not in GOVERNED_SUFFIXES and relative.name not in GOVERNED_NAMES:
            continue
        full = ROOT / relative
        data = full.read_bytes()
        records.append({
            "path": value,
            "category": category(relative),
            "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
        })
        if relative.suffix.lower() in {".py", ".ps1", ".sh", ".command", ".iss"}:
            text = data.decode("utf-8", errors="replace").lower()
            markers = sorted({marker.strip() for marker in REVIEW_MARKERS if marker in text})
            if markers:
                review.append({"path": value, "markers": markers})
    if not records:
        raise SystemExit("APL-IP-001: governed source inventory is empty")
    payload = {
        "schema_version": 1,
        "scope": "version-controlled Arvectum Proxy Launcher source/build/config files",
        "record_count": len(records),
        "records": records,
        "review_findings": review,
        "human_review_required": True,
        "legal_signoff_required": True,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    print(f"APL-IP-001 source manifest: {len(records)} files; review findings: {len(review)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
